---

- name: Enable a rhsm repository
  community.general.rhsm_repository:
    name: rhel-9-for-x86_64-highavailability-rpms

- name: Install ha and apache
  ansible.builtin.yum:
    name:
      - pcs 
      - pacemaker
      - fence-agents-all 
      - pcp-zeroconf
      - httpd 
      - wget
    state: latest

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: Ensure epel repo present
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: Install proxmox fence agent
  ansible.builtin.yum:
    name: fence-agents-pve
    state: latest

- name: Permit traffic in default zone for pcsd service
  ansible.posix.firewalld:
    service: high-availability
    permanent: yes
    state: enabled

- name: Set HA user password
  ansible.builtin.user:
    name: hacluster
    state: present
    password: "{{ hacluster_password | password_hash('sha512') }}"

- name: Enable the pcsd daemon
  ansible.builtin.service:
    name: pcsd
    enabled: yes

- name: Start service pcsd daemon, if not started
  ansible.builtin.service:
    name: pcsd
    state: started

- name: Permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Configure apache resource agent to get the status of apache
  ansible.builtin.template:
    src: templates/status.conf.j2
    dest: /etc/httpd/conf.d/status.conf

- name: Edit the logrotate script supplied with apache so that it does not use systemctl to reload apache
  shell: /bin/systemctl reload httpd.service > /dev/null 2>/dev/null || true
  ignore_errors: yes

- name: Edit the logrotate script supplied with apache so that it does not use systemctl to reload apache
  shell: /usr/bin/test -f /run/httpd.pid >/dev/null 2>/dev/null && /usr/bin/ps -q $(/usr/bin/cat /run/httpd.pid) >/dev/null 2>/dev/null && /usr/sbin/httpd -f /etc/httpd/conf/httpd.conf -c "PidFile /run/httpd.pid" -k graceful > /dev/null 2>/dev/null || true
  ignore_errors: yes

  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot: