---
# tasks file for ha_deploy

# - name: Check if subscription is enabled and setup
#   redhat_subscription:
#     state: present
#     username: root
#     password: {{ rhel_ha_root_user_password }}
#     pool_ids: {{ rhel_ha_pool_id }}

- name: Install iSCSI utils
  ansible.builtin.yum:
    name: iscsi-initiator-utils
    state: latest

- name: Create variable from command
  command: "/sbin/iscsi-iname"
  register: command_output

- set_fact:
    iscsi_iname: "{{ command_output.stdout }}"

- debug: msg="{{iscsi_iname}}"

- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /etc/iscsi/initiatorname.iscsi
    state: touch
    mode: u=rw,g=r,o=r

- name: Test for line
  shell: grep -c "InitiatorName={{ iscsi_iname }}" /etc/iscsi/initiatorname.iscsi || true
  register: test_grep

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    line: "InitiatorName={{ iscsi_iname }}"
  when: test_grep.stdout == "0"




