---
# tasks file for ha_deploy

- name: Check if subscription is enabled and setup
  redhat_subscription:
    state: present
    username: root
    password: {{ rhel_ha_root_user_password }}
    pool_ids: {{ rhel_ha_pool_id }}

- name: Install iSCSI utils
  ansible.builtin.yum:
    name: iscsi-initiator-utils
    state: latest

- name: Create variable from command
  command: "/sbin/iscsi-iname"
  register: command_output

- set_fact:
    iscsi_iname: "{{ command_output.stdout }}"

- debug: msg="{{iscsi_iname}}"

- name: Ensure file exists
  copy:
    content: "InitiatorName={{ iscsi_iname }}"
    dest: /etc/iscsi/initiatorname.iscsi
    force: false
    group: root
    owner: root
    mode: 0644

- name: Create initiator name
  ansible.builtin.copy:
    src: /etc/iscsi/initiatorname.iscsi
    dest: "/etc/iscsi/initiatorname.iscsi.{{ date }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes


