---

- name: Install iscsi client utils
  ansible.builtin.yum:
    name: iscsi-initiator-utils
    state: latest

- name: Create initiatorname variable from command
  command: "/sbin/iscsi-iname"
  register: command_output

- set_fact:
    iscsi_iname: "{{ command_output.stdout }}"

# - debug: msg="{{ iscsi_iname }}"

- name: Touch initiatorname file (create if does not exist)
  ansible.builtin.file:
    path: /etc/iscsi/initiatorname.iscsi
    state: touch
    mode: u=rw,g=r,o=r

- name: Test for initiatorname line
  shell: grep -c "InitiatorName=" /etc/iscsi/initiatorname.iscsi || true
  register: test_grep

- name: Add a line to a file if the file does not exist
  ansible.builtin.lineinfile:
    path: /etc/iscsi/initiatorname.iscsi
    line: "InitiatorName={{ iscsi_iname }}"
  when: test_grep.stdout == "0"

- name: Load data from initiatorname.iscsi file
  slurp:
    src: /etc/iscsi/initiatorname.iscsi
  register: slurped_user_data

- name: Decode data and store as fact
  set_fact:
    iscsi_iname: "{{ slurped_user_data.content | b64decode | trim }}"

- debug: msg="{{ iscsi_iname }}"
  



