---

- debug: msg="{{ iscsi_target_ip }}"

- name: Perform a discovery on 10.1.2.3 and show available target nodes
  community.general.open_iscsi:
    show_nodes: true
    discover: true
    ip: "{{ iscsi_target_ip }}"
  register: command_output

# - debug: msg="{{ command_output.nodes }}"

- set_fact:
    iscsi_target: "{{ command_output.nodes }}"

- debug: msg="{{ iscsi_target }}"

- name: Discover targets on portal and login to the one available
  community.general.open_iscsi:
    portal: "{{ iscsi_target_ip }}"
    login: true
    discover: true
    target: "{{ iscsi_target[0] }}"

# - name: Create physical volume
#   command: pvcreate /dev/sda1

# - name: Create a volume group on top of /dev/sda1
#   community.general.lvg:
#     vg: vg_apache
#     pvs: /dev/sda1

# - name: Create logical volume
#   community.general.lvol:
#     vg: vg_apache
#     lv: lv_apache
#     size: +100%FREE

# - name: Create a ext4 filesystem on /dev/sda1
#   community.general.filesystem:
#     fstype: ext4
#     dev: /dev/vg_apache/lv_apache

- name: Test for initiatorname line
  shell: grep -c "/dev/vg_apache/lv_apache" /etc/fstab || true
  register: test_grep

- name: Add entry into fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/dev/vg_apache/lv_apache /var/www ext4 defaults,_netdev,nofail 0 2"
  when: test_grep.stdout == "0"

- name: Enable a RHSM repository
  community.general.rhsm_repository:
    name: rhel-9-for-x86_64-highavailability-rpms