---

- debug: msg="{{ iscsi_target_ip }}"

- name: Perform a discovery on 10.1.2.3 and show available target nodes
  community.general.open_iscsi:
    show_nodes: true
    discover: true
    ip: "{{ iscsi_target_ip }}"
  register: command_output

# - debug: msg="{{ command_output.nodes }}"

- set_fact:
    iscsi_target: "{{ command_output.nodes }}"

- debug: msg="{{ iscsi_target }}"


# - name: Discover targets on portal and login to the one available
#   community.general.open_iscsi:
#     portal: '{{ iscsi_target }}'
#     login: true
#     discover: true
